spring:
  application:
    name: tienda-backend
  datasource:
    url: jdbc:mysql://localhost:3306/tienda_db
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080